# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 14 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: general
        uses: AdamEECS/metrics@master
        with:
          filename: img/general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: AdamEECS
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Shanghai
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
      - name: habits
        uses: AdamEECS/metrics@master
        with:
          filename: img/habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: AdamEECS
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: user
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_habits_trim: no
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
      - name: achievements
        uses: AdamEECS/metrics@master
        with:
          filename: img/achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: AdamEECS
          template: classic
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          
      - name: achievements-compact
        uses: AdamEECS/metrics@master
        with:
          filename: img/achievements-compact.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: AdamEECS
          template: classic
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B

